#!/bin/sh

### BEGIN INIT INFO
# Provides: enforced
# Required-Start: $local_fs $syslog 
# Required-Stop: $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start enforced to enforce file and folder permsisions.
# Description: Start enforced to enforce file and folder permsisions.
### END INIT INFO

PIDFILE=/var/run/enforced.pid
DAEMON=/usr/local/bin/enforced
DAEMON_ARGS="--syslog --config /etc/enforced.yml"

case $1 in
  start)
    /sbin/start-stop-daemon --start --background --make-pidfile --pidfile "$PIDFILE" --startas $DAEMON -- $DAEMON_ARGS
    ;;
  stop)
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --retry 1
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/enforced {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
